dist: xenial
language: node_js
os:
  - linux
node_js:
- 14
- 12
- 10
stages:
  - lint
  - test
  - e2e
  - deploy
install: if [ -z "$TRAVIS_TAG" ]; then npm install; fi
script: if [ -z "$TRAVIS_TAG" ]; then npm test; fi
jobs:
  include:
    - stage: lint
      if: tag IS blank
      install: npm install standard@14
      script: npm run lint
    - stage: e2e
      if: tag IS blank
      script: npm test && npm run e2e
      after_success: npm run coverage
    - stage: deploy
      if: tag IS present
      node_js: 12
      install: skip
      script: skip
      deploy:
        provider: npm
        email: npmjs.org@kimminich.de
        api_token:
          secure: rimqXeHE0tzIJTzyUvfHbDpQ/E34MKRglvkganNo/Z0Q9A4l/Yx5YVU+J7+BBhC6Tj5Dek93RPPvwkIflfZAoLIKROz3UvrHvXjsU36T1lkRysRpLdsQ6Vp5CcudGlSOGPDU05955z/hnirr4HwgX2ffh6vMvfIpRhEgk4gEpwSjlphKcetlX8aE4QTKJcfWzV2bH+7rbQbVjkOP1GDuTCizVsWdbN/08XypiB6rBbNa3guBrORG9CafQxIV3xdwiKSDtB7PLh4d7qWlmhKmNhbx1iTTWVPrc2R+LDu/3Y9TKh8p9F7r4WGevat/SZ3nbgr5we0xohUYLvxYkelYL4kzZCK8KTjpc0XpsBD0n3E07xSy7OXlPB2gyfW6nnVr4MpUIgq+TIxwjhTcWcGmDMTp/F7h8srvv1dRjVqLbtHkvTIdVIs6UVIS/X2jI46/AgreGMpMRupX1xovprUcnYMP91MqVskRuHCfbGqsS+dtrllWEghpV22SdVXCy6/Prms1MiBYe84d80B8IpiGbivhTAUiCoVmWF71/fe6flGEPV1ZS5do/AaF/ccVFCtHL2QCBPt9e99efjaS/ZKXBkhTuYqCsi5Z6mthqD1b7kaK09VeNJNfqZF0IbNtfEEi1rcrr0WGWii7pu+1OE+n9do/kDYJJ0Ry9dD9snyv5rY=
        on:
          repo: bkimminich/juice-shop-ctf
          tags: true
notifications:
  webhooks:
    urls:
      - secure: a928aEjEBO4FEuLpg1vwl2aiN6li6H9jwgqSV0/XGvvIk/yycFp263zsRgW1e7X4kmyKLwXA+e75kUFnTNU832ZI52Q47DXmZIHxwKWmryfXlhPZ+OF6MJrNjMQQTkLzgEIGXAYf02TpPV883unB9Tr6oCPZk4DkPo4rzYHzwGgUuMC+2zmiHR743xj3gTwnjZB07/NBp2nxOUhr92s1RsDXT4cBB/4ugw0RlWx0ETE7j7a0xqa4hYcn+2JPXbONjrWkS8KZKk06fQr8tTAAOWwQBIgcUzB6izmCuD3oDddv9mxHgaKOgoZMaqqR1Da5hB8MnHft0z6tRjHxd/CH3qSQJ4KB7rTUJr+18wqfqUQff6dCzuTRNpXBYx8Q8YnKk84VG99jQQXHOHGSTBZnIy/c2OPMhD8d+gBvfPSmRutZjw7iq2epYEf+DhtDEivkvCFQkVLjtj5wH6UYYWY+NluTV7Asiss7MiDvxSERabE4uDuix2mjGn/ztRusxPyAwOIAHIRSAE/821Qu/BGSzFPOnsuO/G1wcevrm73PxC2ZETNgMnItZsxaZorDHQWyGUP74bLViZE6FTM/4Ip4Oc9Ho47sXn8GAyky6INrs5/f08FjeZ1o3S6XUCYOFmKbIX4Z41aG6bRg77GZC9kt9QC6Yjda4QPLqBHvgmlxxAU=
    on_success: always
    on_failure: always
    on_start: never
  slack:
    rooms:
      - secure: XmMZn4PEkk3UfowEhOq3Nio9cn92cEDEDmqOCa1Lqy/zQ4YGD6I+3IeHbKEQb6hwy5TqRV96c3zu8hVoXv3I4eOc/LZLhXJ15yRbL6iI1sf+Ba1i4SSdSaF5o92C5C+O6bPrkbrI2ZJZgyD3d9/d8kWFXrBoEIojDjqQ3e08MDqdlRKwGbvbXi/vOj/jUBpnz1v4TgonwU+tQP7CyxEw0bDnS+jFH99ZB7gt2l15S4/werrmsBqlTbgRtP04EmMcdDpWFzA1I/mOAzdwvu/oXc88vTqgc5eqARW9r7+cIZMxBK/Ip7PZOGFnj7oBtl4N3DLxrsmSV5I1/NGLkB78a7vzoVD05K69i5M23QPVZRojoBp67tpgu85v4SbENki6ewoHMnXBUMkum0UaTEJeOCzjTJf/dstAakvxVNMtQs59totMaCWQt1A12nTNXSHJi1PI882E/U2GApBrr0n2by9FjzzWN4SKKEcr7jiQwEaw6TXyDCiA9VlIyVigeXWA5yW3J6XV/4KggtVtdsWcmVC6AvGEQZiRHKY7gaq8Ih/205gOC6hBAJfmh7IwuwLPo1LCnoy/E3q7q78lSoWlS7XOlA0OckzkIrO38q/VbLIGnZnB71WFa+ib6IHdZDdGZtrBAYS3Mjcj94L+/aPwXN2MTv0lynRadzGS6m51I2w=
    on_success: change
    on_failure: change
    on_pull_requests: false
